# Generated by Django 3.2.8 on 2021-10-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_sysid', models.CharField(default=True, max_length=30, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.CharField(default=True, max_length=30, null=True)),
                ('humidity', models.CharField(default=True, max_length=30, null=True)),
                ('pm1_in', models.CharField(default=True, max_length=30, null=True)),
                ('pm25_in', models.CharField(default=True, max_length=30, null=True)),
                ('pm10_in', models.CharField(default=True, max_length=30, null=True)),
                ('pm1_out', models.CharField(default=True, max_length=30, null=True)),
                ('pm10_out', models.CharField(default=True, max_length=30, null=True)),
                ('pm25_out', models.CharField(default=True, max_length=30, null=True)),
                ('latitude', models.CharField(default=True, max_length=30, null=True)),
                ('longitude', models.CharField(default=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'cf_sensor_values',
            },
        ),
    ]
